# Generated by Django 5.2.6 on 2025-11-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('assessment', models.IntegerField(verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Учебная Практика',
                'verbose_name_plural': 'Учебная Практика',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('surname2', models.CharField(default='', max_length=50, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(verbose_name='Пол')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['surname', 'name', 'surname2'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('assessment', models.IntegerField(verbose_name='Оценка')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courseapp.group')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.group')),
                ('students_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courseapp.group')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журнал',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('surname2', models.CharField(default='', max_length=50, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(verbose_name='Пол')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.group')),
                ('practice_id', models.ManyToManyField(to='courseapp.practice')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['surname', 'name', 'surname2'],
            },
        ),
        migrations.AddField(
            model_name='practice',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.teachers'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.teachers'),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('group_id', models.ManyToManyField(to='courseapp.group')),
                ('teachers_id', models.ManyToManyField(to='courseapp.teachers')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
