# Generated by Django 5.2.6 on 2025-11-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='teachers_id',
            new_name='teachers',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='students_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='practice',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='group_id',
            new_name='groups',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='group_id',
        ),
    ]
