# Generated by Django 5.2.6 on 2025-11-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_rename_group_id_courses_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='practice_id',
        ),
        migrations.AddField(
            model_name='group',
            name='practice_id',
            field=models.ManyToManyField(to='courseapp.practice'),
        ),
    ]
