# Generated by Django 5.2.6 on 2025-11-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_remove_students_practice_id_group_practice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='practice_id',
            new_name='practice',
        ),
    ]
