# Generated by Django 5.2.6 on 2025-12-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_rename_practice_id_group_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Description',
            field=models.CharField(default=1, max_length=1000, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
