# Generated by Django 5.2.6 on 2025-12-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0005_courses_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Detailed_description',
            field=models.CharField(default=1, max_length=1000, verbose_name='Подробное описание'),
            preserve_default=False,
        ),
    ]
