# Generated by Django 6.0 on 2025-12-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0006_courses_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Detailed_description',
            field=models.TextField(verbose_name='Подробное описание'),
        ),
    ]
